### ISSUE TITLE
Subscription API - EDIT

### ISSUE THREAD

**Issue by yulque** [PrivateSub-project/PrivateSub#138]
User story
User wants to click each subscription and edit proper to detailed information. For this, an API is needed to fetch the data.

Description
API is needed to edit the data for subscription details

Acceptance Criteria
The API edits and returns the proper data for a testing subscription.

Testing
The API edits and returns the proper data on request of getting a subscription detailed information from the database.

**Comment by nostojic** [comment]
Tested and completed.
