### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by karouhifar** [PrivateSub-project/PrivateSub#51]
User Story
As a user, I would like to create an account in PrivateSub, so that I can be able to get authenticated in login page.

Description
Register account can create and save User data such as name , Email , password, and match password

Acceptance Criteria
post the JSON data to database server
Unverified users must get response of Http 401 error.
Verified users have an account and redirect to login with Http 201 create.

Testing
No errors
No conflicts
No invalid password matches

**Comment by bjam3s** [comment]
Created register route on the back end. Data gets stored, checked with postman and mongodb. Ready to be used on deployed heroku.
