### ISSUE TITLE
Write Add Funds to Credit Card API route

### ISSUE THREAD

**Issue by nostojic** [PrivateSub-project/PrivateSub#76]
User Story
The user add funds to a virtual credit card

Description
The user needs to add funds to a credit card before it can be used.

Acceptance Criteria
User is able to add funds to a credit card.

Testing
Try to add funds to a credit card.

**Comment by karouhifar** [comment]
Refreshing a page is to use vanilla JavaScript 'window.location.reload(false);'

**Comment by nostojic** [comment]
Tested and complete
